name: "My composite action"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  
  steps:
  - name: "Checkout"
    uses: actions/checkout@v2

  - name: Login via Az Module
    uses: azure/login@v1
    with:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      enable-AzPSSession: true
  