# name: Build, Test & Deploy
# on: push

# env:
#   AZURE_FUNCTIONAPP_NAME: 'functionsdemoapps'   # set this to your function app name on Azure
#  # AZURE_FUNCTIONAPP_PACKAGE_PATH: './HelloWord/dotnet'       # set this to the path to your function app project, defaults to the repository root
#  # DOTNET_VERSION: '6.0.x'

#   RESOURCE_GROUP_NAME: 'MyApps'

# jobs:
#   deploy-with-publish-profile:
#     name: 'FunctionApp Build, Test & Deploy'
#     runs-on: windows-latest

#     steps:
#     - name: Checkout the repo
#       uses: actions/checkout@v2

#     - name: Login via Az Module
#       uses: azure/login@v1
#       with:
#          creds: ${{secrets.AZURE_CREDENTIALS}}
#          enable-AzPSSession: true

#     # - name: Get publish Profile
#     #   id: fncapp
#     #   shell: pwsh
#     #   run: |
#     #     $profile = Get-AzWebAppPublishingProfile `
#     #         -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }} `
#     #         -Name ${{ env.FUNCTION_APP_NAME }}
#     #     $profile = $profile.Replace("`r", "").Replace("`n", "")
#     #     Write-Output "::set-output name=profile::$profile"

#     - name: Get WebApp/FunctionApp publish profile
#       id: fncapp
#       uses: aliencube/publish-profile-actions@v1
#       env:
#         AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
#       with:
#         resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
#         appName: ${{ env.AZURE_FUNCTIONAPP_NAME }}    
              
#     - name: Show publish profile
#       shell: pwsh
#       run: |
#             echo ${{ steps.fncapp.outputs.profile }}

#     - name: Deploy FunctionApp
#       uses: Azure/functions-action@v1
#       with:
#         app-name: ${{ env.FUNCTION_APP_NAME }}
#         package: published
#         publish-profile: ${{ steps.fncapp.outputs.profile }}

#     - name: Reset publish Profile
#       shell: pwsh
#       run: |
#         $profile = Reset-AzWebAppPublishingProfile `
#             -ResourceGroupName ${{ env.RESOURCE_GROUP_NAME }} `
#             -Name ${{ env.FUNCTION_APP_NAME }}
#         $profile = "" 