name: CI/CD.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      hello-world-dotnet: ${{ steps.filter.outputs.hello-world-dotnet }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hello-world-dotnet:
              - 'HelloWord/dotnet/**'
            frontend:
              - 'frontend/**'

  # JOB to build and test backend code
  hello-world-dotnet:
    needs: changes
    if: ${{ needs.changes.outputs.hello-world-dotnet == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: ./.github/workflows/HelloWorld/dotnet

  # JOB to build and test frontend code
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
