name: CI/CD.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      hello-world-dotnet: ${{ steps.filter.outputs.hello-world-dotnet }}
      hello-world-js: ${{ steps.filter.outputs.hello-world-js }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hello-world-dotnet:
              - 'HelloWord/dotnet/**'
            hello-world-js :
              - 'HelloWord/js/**'

  # JOB to build and test backend code
  hello-world-dotnet:
    needs: changes
    # if: ${{ needs.changes.outputs.hello-world-dotnet == 'true' }}
    # runs-on: ubuntu-latest
    # uses: ./.github/workflows/Hellow-World-dotnet.yml@master
    uses: ./.github/workflows/Hellow-World-dotnet.yml

  # JOB to build and test frontend code
  hello-world-js:
    needs: changes
    if: ${{ needs.changes.outputs.hello-world-js == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
